// In this file you can specify the trial data for your experiment


const trial_info = {
    key_press: [
        {
          picture:"images/1_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown: "1",
          dregreesofrotation:"50",
        },
        {
          picture:"images/1_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"1",
          dregreesofrotation: "50",
        },
        {
          picture:"images/1_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"1",
          dregreesofrotation: "150",
        },
        {
          picture:"images/1_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"1",
          dregreesofrotation: "150",
        },
        {
          picture:"images/2_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"2",
          dregreesofrotation: "50",
        },
        {
          picture:"images/2_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"2",
          dregreesofrotation: "50",
        },
        {
          picture:"images/2_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"2",
          dregreesofrotation: "150",
        },
        {
          picture:"images/2_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"2",
          dregreesofrotation: "150",
        },
        {
          picture:"images/3_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"3",
          dregreesofrotation: "50",
        },
        {
          picture:"images/3_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"3",
          dregreesofrotation: "50",
        },
        {
          picture:"images/3_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"3",
          dregreesofrotation: "150",
        },
        {
          picture:"images/3_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"3",
          dregreesofrotation: "150",
        },

    ]
};

const trial_info2 = {
    key_press: [

        {
          picture:"images/4_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"4",
          dregreesofrotation: "50",
        },
        {
          picture:"images/4_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"4",
          dregreesofrotation: "50",
        },
        {
          picture:"images/4_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"4",
          dregreesofrotation: "150",
        },
        {
          picture:"images/4_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"4",
          dregreesofrotation: "150",
        },
        {
          picture:"images/5_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown: "5",
          dregreesofrotation:"50",
        },
        {
          picture:"images/5_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"5",
          dregreesofrotation: "50",
        },
        {
          picture:"images/5_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"5",
          dregreesofrotation: "150",
        },
        {
          picture:"images/5_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"5",
          dregreesofrotation: "150",
        },
        {
          picture:"images/6_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"6",
          dregreesofrotation: "50",
        },
        {
          picture:"images/6_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"6",
          dregreesofrotation: "50",
        },
        {
          picture:"images/6_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"6",
          dregreesofrotation: "150",
        },
        {
          picture:"images/6_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"6",
          dregreesofrotation: "150",
        },
        {
          picture:"images/7_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"7",
          dregreesofrotation: "50",
        },
        {
          picture:"images/7_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"7",
          dregreesofrotation: "50",
        },
        {
          picture:"images/7_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"7",
          dregreesofrotation: "150",
        },
        {
          picture:"images/7_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"7",
          dregreesofrotation: "150",
        },
        {
          picture:"images/8_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"8",
          dregreesofrotation: "50",
        },
        {
          picture:"images/8_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"8",
          dregreesofrotation: "50",
        },
        {
          picture:"images/8_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"8",
          dregreesofrotation: "150",
        },
        {
          picture:"images/8_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"8",
          dregreesofrotation: "150",
        },
        {
          picture:"images/9_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown: "9",
          dregreesofrotation:"50",
        },
        {
          picture:"images/9_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"9",
          dregreesofrotation: "50",
        },
        {
          picture:"images/9_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"9",
          dregreesofrotation: "150",
        },
        {
          picture:"images/9_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"9",
          dregreesofrotation: "150",
        },
        {
          picture:"images/10_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"10",
          dregreesofrotation: "50",
        },
        {
          picture:"images/10_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"10",
          dregreesofrotation: "50",
        },
        {
          picture:"images/10_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"10",
          dregreesofrotation: "150",
        },
        {
          picture:"images/10_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"10",
          dregreesofrotation: "150",
        },
        {
          picture:"images/11_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"11",
          dregreesofrotation: "50",
        },
        {
          picture:"images/11_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"11",
          dregreesofrotation: "50",
        },
        {
          picture:"images/11_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"11",
          dregreesofrotation: "150",
        },
        {
          picture:"images/11_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"11",
          dregreesofrotation: "150",
        },
        {
          picture:"images/12_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"12",
          dregreesofrotation: "50",
        },
        {
          picture:"images/12_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"12",
          dregreesofrotation: "50",
        },
        {
          picture:"images/12_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"12",
          dregreesofrotation: "150",
        },
        {
          picture:"images/12_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"12",
          dregreesofrotation: "150",
        },
        {
          picture:"images/13_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown: "13",
          dregreesofrotation:"50",
        },
        {
          picture:"images/13_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"13",
          dregreesofrotation: "50",
        },
        {
          picture:"images/13_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"13",
          dregreesofrotation: "150",
        },
        {
          picture:"images/13_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"13",
          dregreesofrotation: "150",
        },
        {
          picture:"images/14_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"14",
          dregreesofrotation: "50",
        },
        {
          picture:"images/14_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"14",
          dregreesofrotation: "50",
        },
        {
          picture:"images/14_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"14",
          dregreesofrotation: "150",
        },
        {
          picture:"images/14_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"14",
          dregreesofrotation: "150",
        },
        {
          picture:"images/15_50_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"15",
          dregreesofrotation: "50",
        },
        {
          picture:"images/15_50_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"15",
          dregreesofrotation: "50",
        },
        {
          picture:"images/15_150_different.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"different",
          numberpictureshown:"15",
          dregreesofrotation: "150",
        },
        {
          picture:"images/15_150_same.jpg",
          key1:"f",
          key2:"j",
          f:"same",
          j:"different",
          expected:"same",
          numberpictureshown:"15",
          dregreesofrotation: "150",
        },

  ]
};
